import { ManholeAsset, PumpStationAsset, PipeAsset, AssetSummaryStats } from '../types/asset';
import { InspectionRecord } from '../types/inspection';
import { UserProfile } from '../types/rbac';

export const INITIAL_MANHOLES: ManholeAsset[] = [
  // Zone A - Collectors
  {
    id: 'mh-101',
    assetCode: 'MH-101',
    name: 'Manhole Utama Jl. Sudirman A1',
    type: 'manhole',
    area: 'Zone A - Sudirman',
    status: 'Active',
    condition: 'Good',
    installationYear: 2019,
    lastInspectedAt: '2026-08-15',
    nextInspectionDue: '2026-11-15',
    coordinates: { lat: -6.2088, lng: 106.8226, elevation: 12.4 },
    depthMeters: 3.5,
    diameterMm: 1000,
    material: 'Precast Concrete',
    coverCondition: 'Good - Sealed',
    photos: ['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=600&q=80']
  },
  {
    id: 'mh-102',
    assetCode: 'MH-102',
    name: 'Manhole Cabang Jl. Sudirman A2',
    type: 'manhole',
    area: 'Zone A - Sudirman',
    status: 'Active',
    condition: 'Fair',
    installationYear: 2019,
    lastInspectedAt: '2026-07-20',
    nextInspectionDue: '2026-10-20',
    coordinates: { lat: -6.2105, lng: 106.8238, elevation: 11.8 },
    depthMeters: 3.8,
    diameterMm: 1000,
    material: 'Precast Concrete',
    coverCondition: 'Fair - Minor Rust',
    photos: ['https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=600&q=80']
  },
  {
    id: 'mh-103',
    assetCode: 'MH-103',
    name: 'Manhole Kolektor Setiabudi B1',
    type: 'manhole',
    area: 'Zone A - Setiabudi',
    status: 'Active',
    condition: 'Warning',
    installationYear: 2018,
    lastInspectedAt: '2026-06-10',
    nextInspectionDue: '2026-09-10',
    coordinates: { lat: -6.2128, lng: 106.8255, elevation: 10.5 },
    depthMeters: 4.2,
    diameterMm: 1200,
    material: 'Precast Concrete',
    coverCondition: 'Warning - Heavy Sediment Build-up',
    photos: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80']
  },
  {
    id: 'mh-104',
    assetCode: 'MH-104',
    name: 'Manhole Simpang Manggarai C1',
    type: 'manhole',
    area: 'Zone A - Manggarai',
    status: 'Active',
    condition: 'Critical',
    installationYear: 2017,
    lastInspectedAt: '2026-08-01',
    nextInspectionDue: '2026-08-25',
    coordinates: { lat: -6.2152, lng: 106.8280, elevation: 9.2 },
    depthMeters: 4.8,
    diameterMm: 1500,
    material: 'Precast Concrete',
    coverCondition: 'Critical - Structural Crack & High Overflow Risk',
    photos: ['https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=600&q=80']
  },
  {
    id: 'mh-105',
    assetCode: 'MH-105',
    name: 'Manhole Feeder Tebet West D1',
    type: 'manhole',
    area: 'Zone B - Tebet',
    status: 'Active',
    condition: 'Good',
    installationYear: 2021,
    lastInspectedAt: '2026-08-10',
    nextInspectionDue: '2026-11-10',
    coordinates: { lat: -6.2180, lng: 106.8310, elevation: 8.7 },
    depthMeters: 3.2,
    diameterMm: 800,
    material: 'HDPE',
    coverCondition: 'Good - New Composite',
    photos: []
  },
  {
    id: 'mh-106',
    assetCode: 'MH-106',
    name: 'Manhole Feeder Tebet Central D2',
    type: 'manhole',
    area: 'Zone B - Tebet',
    status: 'Active',
    condition: 'Fair',
    installationYear: 2021,
    lastInspectedAt: '2026-07-01',
    nextInspectionDue: '2026-10-01',
    coordinates: { lat: -6.2205, lng: 106.8335, elevation: 8.1 },
    depthMeters: 3.4,
    diameterMm: 800,
    material: 'HDPE',
    coverCondition: 'Good',
    photos: []
  },
  {
    id: 'mh-107',
    assetCode: 'MH-107',
    name: 'Manhole Kolektor Utama Pluit North E1',
    type: 'manhole',
    area: 'Zone C - Pluit',
    status: 'Active',
    condition: 'Good',
    installationYear: 2020,
    lastInspectedAt: '2026-08-18',
    nextInspectionDue: '2026-11-18',
    coordinates: { lat: -6.2050, lng: 106.8210, elevation: 13.1 },
    depthMeters: 3.0,
    diameterMm: 1000,
    material: 'Precast Concrete',
    coverCondition: 'Good',
    photos: []
  },
  {
    id: 'mh-108',
    assetCode: 'MH-108',
    name: 'Manhole Sub-Kolektor Pluit East E2',
    type: 'manhole',
    area: 'Zone C - Pluit',
    status: 'Active',
    condition: 'Warning',
    installationYear: 2020,
    lastInspectedAt: '2026-05-15',
    nextInspectionDue: '2026-08-15', // Overdue!
    coordinates: { lat: -6.2070, lng: 106.8195, elevation: 12.8 },
    depthMeters: 3.2,
    diameterMm: 800,
    material: 'Precast Concrete',
    coverCondition: 'Warning - Odour Leakage Reported',
    photos: []
  }
];

export const INITIAL_PUMP_STATIONS: PumpStationAsset[] = [
  {
    id: 'ps-001',
    assetCode: 'PS-001',
    name: 'Stasiun Pompa Utama Manggarai (WWTP Terminal 1)',
    type: 'pump_station',
    area: 'Zone A - Manggarai',
    status: 'Active',
    condition: 'Good',
    installationYear: 2017,
    lastInspectedAt: '2026-08-20',
    nextInspectionDue: '2026-09-20',
    coordinates: { lat: -6.2168, lng: 106.8298, elevation: 7.5 },
    capacityLps: 450,
    pumpCount: 4,
    activePumps: 3,
    powerSource: 'PLN Primary + Dual Genset Backup',
    photos: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80']
  },
  {
    id: 'ps-002',
    assetCode: 'PS-002',
    name: 'Stasiun Pompa Booster Tebet South',
    type: 'pump_station',
    area: 'Zone B - Tebet',
    status: 'Active',
    condition: 'Fair',
    installationYear: 2021,
    lastInspectedAt: '2026-07-25',
    nextInspectionDue: '2026-10-25',
    coordinates: { lat: -6.2230, lng: 106.8360, elevation: 6.8 },
    capacityLps: 220,
    pumpCount: 2,
    activePumps: 2,
    powerSource: 'PLN Primary + Genset Backup',
    photos: []
  }
];

export const INITIAL_PIPES: PipeAsset[] = [
  // Chain: MH-107 -> MH-108 -> MH-101 -> MH-102 -> MH-103 -> MH-104 -> PS-001
  {
    id: 'p-001',
    assetCode: 'P-001',
    name: 'Pipa Main Trunk Pluit North 01',
    type: 'pipe',
    area: 'Zone C - Pluit',
    status: 'Active',
    condition: 'Good',
    installationYear: 2020,
    lastInspectedAt: '2026-08-18',
    nextInspectionDue: '2026-11-18',
    fromAssetId: 'mh-107',
    toAssetId: 'mh-108',
    diameterMm: 600,
    material: 'HDPE',
    lengthMeters: 280,
    flowDirection: 'downstream',
    slopePercent: 0.8,
    photos: []
  },
  {
    id: 'p-002',
    assetCode: 'P-002',
    name: 'Pipa Collector Pluit to Sudirman 02',
    type: 'pipe',
    area: 'Zone A - Sudirman',
    status: 'Active',
    condition: 'Warning',
    installationYear: 2019,
    lastInspectedAt: '2026-05-15',
    nextInspectionDue: '2026-08-15',
    fromAssetId: 'mh-108',
    toAssetId: 'mh-101',
    diameterMm: 600,
    material: 'HDPE',
    lengthMeters: 350,
    flowDirection: 'downstream',
    slopePercent: 0.9,
    photos: []
  },
  {
    id: 'p-003',
    assetCode: 'P-003',
    name: 'Pipa Utama Sudirman Segment A1-A2',
    type: 'pipe',
    area: 'Zone A - Sudirman',
    status: 'Active',
    condition: 'Good',
    installationYear: 2019,
    lastInspectedAt: '2026-08-15',
    nextInspectionDue: '2026-11-15',
    fromAssetId: 'mh-101',
    toAssetId: 'mh-102',
    diameterMm: 800,
    material: 'Precast Concrete',
    lengthMeters: 240,
    flowDirection: 'downstream',
    slopePercent: 1.1,
    photos: []
  },
  {
    id: 'p-004',
    assetCode: 'P-004',
    name: 'Pipa Sudirman to Setiabudi Segment A2-B1',
    type: 'pipe',
    area: 'Zone A - Setiabudi',
    status: 'Active',
    condition: 'Fair',
    installationYear: 2019,
    lastInspectedAt: '2026-07-20',
    nextInspectionDue: '2026-10-20',
    fromAssetId: 'mh-102',
    toAssetId: 'mh-103',
    diameterMm: 800,
    material: 'Precast Concrete',
    lengthMeters: 310,
    flowDirection: 'downstream',
    slopePercent: 1.0,
    photos: []
  },
  {
    id: 'p-005',
    assetCode: 'P-005',
    name: 'Pipa Kolektor Setiabudi to Manggarai',
    type: 'pipe',
    area: 'Zone A - Manggarai',
    status: 'Active',
    condition: 'Critical',
    installationYear: 2018,
    lastInspectedAt: '2026-08-01',
    nextInspectionDue: '2026-08-25',
    fromAssetId: 'mh-103',
    toAssetId: 'mh-104',
    diameterMm: 1000,
    material: 'Precast Concrete',
    lengthMeters: 420,
    flowDirection: 'downstream',
    slopePercent: 1.2,
    photos: []
  },
  {
    id: 'p-006',
    assetCode: 'P-006',
    name: 'Pipa Terminal Manggarai to Pump Station PS-001',
    type: 'pipe',
    area: 'Zone A - Manggarai',
    status: 'Active',
    condition: 'Good',
    installationYear: 2017,
    lastInspectedAt: '2026-08-20',
    nextInspectionDue: '2026-11-20',
    fromAssetId: 'mh-104',
    toAssetId: 'ps-001',
    diameterMm: 1200,
    material: 'Precast Concrete',
    lengthMeters: 260,
    flowDirection: 'downstream',
    slopePercent: 1.5,
    photos: []
  },

  // Tebet Branch: MH-105 -> MH-106 -> PS-002 -> (Pipe to PS-001)
  {
    id: 'p-007',
    assetCode: 'P-007',
    name: 'Pipa Feeder Tebet West to Central',
    type: 'pipe',
    area: 'Zone B - Tebet',
    status: 'Active',
    condition: 'Good',
    installationYear: 2021,
    lastInspectedAt: '2026-08-10',
    nextInspectionDue: '2026-11-10',
    fromAssetId: 'mh-105',
    toAssetId: 'mh-106',
    diameterMm: 500,
    material: 'HDPE',
    lengthMeters: 380,
    flowDirection: 'downstream',
    slopePercent: 0.7,
    photos: []
  },
  {
    id: 'p-008',
    assetCode: 'P-008',
    name: 'Pipa Feeder Tebet to Booster Pump PS-002',
    type: 'pipe',
    area: 'Zone B - Tebet',
    status: 'Active',
    condition: 'Fair',
    installationYear: 2021,
    lastInspectedAt: '2026-07-01',
    nextInspectionDue: '2026-10-01',
    fromAssetId: 'mh-106',
    toAssetId: 'ps-002',
    diameterMm: 500,
    material: 'HDPE',
    lengthMeters: 390,
    flowDirection: 'downstream',
    slopePercent: 0.8,
    photos: []
  },
  {
    id: 'p-009',
    assetCode: 'P-009',
    name: 'Pipa Pressurized Sub-Trunk PS-002 to PS-001',
    type: 'pipe',
    area: 'Zone B - Tebet',
    status: 'Active',
    condition: 'Good',
    installationYear: 2021,
    lastInspectedAt: '2026-07-25',
    nextInspectionDue: '2026-10-25',
    fromAssetId: 'ps-002',
    toAssetId: 'ps-001',
    diameterMm: 700,
    material: 'Ductile Iron',
    lengthMeters: 920,
    flowDirection: 'downstream',
    slopePercent: 0.5,
    photos: []
  }
];

export const INITIAL_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'insp-001',
    assetId: 'mh-104',
    assetCode: 'MH-104',
    assetName: 'Manhole Simpang Manggarai C1',
    inspectionDate: '2026-08-01',
    inspectorName: 'Budi Santoso',
    inspectorRole: 'Technician',
    condition: 'Critical',
    issueCategory: 'Overflow',
    notes: 'Terjadi penyumbatan sedimen berat di mulut pipa outlet. Retakan terlihat pada struktur dinding bagian atas.',
    photos: ['https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=600&q=80'],
    actionTaken: 'Jadwal flushing dan pengerukan sedimen darurat dibuat.',
    requiresFollowUp: true
  },
  {
    id: 'insp-002',
    assetId: 'mh-103',
    assetCode: 'MH-103',
    assetName: 'Manhole Kolektor Setiabudi B1',
    inspectionDate: '2026-06-10',
    inspectorName: 'Ahmad Rizki',
    inspectorRole: 'Engineer',
    condition: 'Warning',
    issueCategory: 'Sedimentation',
    notes: 'Endapan pasir dan lemak mencatatkan ketebalan ~20cm di dasar manhole. Aliran air lambat.',
    photos: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80'],
    requiresFollowUp: true
  },
  {
    id: 'insp-003',
    assetId: 'ps-001',
    assetCode: 'PS-001',
    assetName: 'Stasiun Pompa Utama Manggarai',
    inspectionDate: '2026-08-20',
    inspectorName: 'Eko Prasetyo',
    inspectorRole: 'Engineer',
    condition: 'Good',
    issueCategory: 'Normal / Routine',
    notes: 'Pemeriksaan rutin 3 unit pompa submersible berjalan optimal. Tingkat getaran dan oli normal.',
    photos: [],
    requiresFollowUp: false
  }
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-001',
    name: 'Deni Ardiansyah',
    email: 'admin@sewerbita.id',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    department: 'Sistem Informasi & Infrastructure'
  },
  {
    id: 'usr-002',
    name: 'Budi Santoso',
    email: 'budi.santoso@sewerbita.id',
    role: 'Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    department: 'Operasional Jaringan Air Limbah'
  },
  {
    id: 'usr-003',
    name: 'Ahmad Rizki',
    email: 'ahmad.rizki@sewerbita.id',
    role: 'Technician',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    department: 'Tim Pemeliharaan Lapangan'
  },
  {
    id: 'usr-004',
    name: 'Ir. Hendra Kusuma',
    email: 'hendra.management@sewerbita.id',
    role: 'Management',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    department: 'Direksi Operasional'
  }
];
